apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: sandbox
  labels:
    app: test
  # namespace: default
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: 562114208112.dkr.ecr.us-east-1.amazonaws.com/rawcaster-python-api:Latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rawcaster-secret-env
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: test
  name: test
  namespace: sandbox
spec:
  type: NodePort
  ports:
    - name: test
      port: 80
      targetPort: 80
  selector:
    app: test