apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: dev
  labels:
    app: user
  # namespace: default
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 562114208112.dkr.ecr.us-east-1.amazonaws.com/rawcaster-python-api:ai_and_chime
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rawcaster-secret-env
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: user
  name: user
  namespace: dev
spec:
  type: NodePort
  ports:
    - name: user
      port: 80
      targetPort: 80
  selector:
    app: user
