from sqlalchemy import Column, Integer, String,BigInteger, DateTime, Date,Text,DECIMAL
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.mysql import TINYINT,TINYTEXT
from app.db.base_class import Base

class User(Base):
    id=Column(Integer,primary_key=True)
    user_ref_id=Column(String(25))
    email_id=Column(String(100))
    is_email_id_verified=Column(TINYINT(1),comment=" 0->No, 1->Yes ")
    password=Column(String(250))
    first_name=Column(String(100))
    last_name=Column(String(100))
    display_name=Column(String(100))
    gender=Column(TINYINT(1),comment=" 0->Transgender, 1->Male, 2->Female ")
    dob=Column(Date)
    country_code=Column(String(10))
    mobile_no=Column(BigInteger)
    is_mobile_no_verified=Column(TINYINT(4),comment=" 0->No, 1->Yes ")
    country_id=Column(Integer)
    user_code=Column(String(25),comment=" A unique code for users sharing purpose like refrrer ")
    signup_type=Column(TINYINT(1),comment=" 1->Web, 2->Facebook, 3->Google ")
    signup_social_ref_id=Column(String(100),comment=" reference id from facebook or google ")
    profile_img=Column(String(500))
    cover_image=Column(String(500))
    website=Column(String(100))
    geo_location=Column(TINYTEXT,default= 1,comment=" from google geo location ")
    latitude=Column(DECIMAL(11,7))
    longitude=Column(DECIMAL(11,7))
    user_type_id=Column(Integer,nullable=False,default=1,comment=" ref user_type_master ")
    user_status_id=Column(Integer,nullable=False,default=1,comment=" ref table user_status_master ")
    bio_data=Column(Text)
    created_at=Column(DateTime)
    created_by=Column(Integer)
    online=Column(TINYINT(1),nullable=False,default=0)
    web_online=Column(TINYINT(1),nullable=False,default=0)
    app_online=Column(TINYINT(1),nullable=False,default=0)
    last_seen=Column(DateTime)
    admin_verified_status=Column(TINYINT(1),default=1,nullable=False,comment=" 1-approved 0-pending ")
    referrer_id=Column(Integer)
    invited_date=Column(DateTime)
    referral_expiry_date=Column(DateTime)
    total_referral_point=Column(Integer,nullable=False,default=0)
    unused_referral_points=Column(Integer,nullable=False,default=0)
    influencer_category=Column(String(20))
    status=Column(TINYINT(1),comment=" 0->verification pending, 1->Active, 2->Suspended, 3->Blocked, 4->Deleted ")