"""initial alembic

Revision ID: 7fb86e8beb3c
Revises: 
Create Date: 2023-03-22 15:46:35.817311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb86e8beb3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ref_id', sa.String(length=25), nullable=True),
    sa.Column('email_id', sa.String(length=100), nullable=True),
    sa.Column('is_email_id_verified', mysql.TINYINT(display_width=1), nullable=True, comment=' 0->No, 1->Yes '),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('gender', mysql.TINYINT(display_width=1), nullable=True, comment=' 0->Transgender, 1->Male, 2->Female '),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('mobile_no', sa.BigInteger(), nullable=True),
    sa.Column('is_mobile_no_verified', mysql.TINYINT(display_width=4), nullable=True, comment=' 0->No, 1->Yes '),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('user_code', sa.String(length=25), nullable=True, comment=' A unique code for users sharing purpose like refrrer '),
    sa.Column('signup_type', mysql.TINYINT(display_width=1), nullable=True, comment=' 1->Web, 2->Facebook, 3->Google '),
    sa.Column('signup_social_ref_id', sa.String(length=100), nullable=True, comment=' reference id from facebook or google '),
    sa.Column('profile_img', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('geo_location', mysql.TINYTEXT(), nullable=True, comment=' from google geo location '),
    sa.Column('latitude', sa.DECIMAL(precision=11, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=7), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=False, comment=' ref user_type_master '),
    sa.Column('user_status_id', sa.Integer(), nullable=False, comment=' ref table user_status_master '),
    sa.Column('bio_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('web_online', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('app_online', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('admin_verified_status', mysql.TINYINT(display_width=1), nullable=False, comment=' 1-approved 0-pending '),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('invited_date', sa.DateTime(), nullable=True),
    sa.Column('referral_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('total_referral_point', sa.Integer(), nullable=False),
    sa.Column('unused_referral_points', sa.Integer(), nullable=False),
    sa.Column('influencer_category', sa.String(length=20), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment=' 0->verification pending, 1->Active, 2->Suspended, 3->Blocked, 4->Deleted '),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
