"""initial alembic

Revision ID: 897aa63783c5
Revises: 7fb86e8beb3c
Create Date: 2023-03-22 15:48:24.376897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897aa63783c5'
down_revision = '7fb86e8beb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
