name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/aws-configure-credentials@v1
      with:
        aws-access-key-id: AKIAYFYE6EFYGNPCA32D
        aws-secret-access-key: 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
        aws-region: us-east-1
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build,tag and push image to Amazon ECR
      env:
        ECR_REGISTRY: rawcasterecr
        ECR_REPOSITORY: rawcasterecr
        IMAGE_TAG: rawcaster-dev
      run:
         docker build -t 
