name: AWS EKS Deployment

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: rawcaster-prod-eks
  ECR_REPOSITORY_NAME: 	rawcaster-python-api-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: release-${{ steps.date.outputs.date }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Install kubectl
      #   run: |
      #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     chmod +x kubectl
      #     sudo mv kubectl /usr/local/bin/
      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --name rawcaster-eks --region us-east-1
      #     kubectl get ns
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rawcaster-python-api-prod
          tags: ai_and_chime
          tag: ${{ steps.date.outputs.date }}

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$tags -t $ECR_REGISTRY/$ECR_REPOSITORY:$tag backend/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$tag
      - name: Deploy to EKS
        # run: |
        #   kubectl rollout restart deployment/user -n dev
